#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                                                                      ║"
echo "║       🔬 DASHBOARD FORENSE HR - ANALISI MANIPOLAZIONI               ║"
echo "║                                                                      ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "🚀 Avvio dashboard forense con analisi statistica..."
echo ""

cd "$(dirname "$0")"

# Verifica se il server è già attivo
if lsof -Pi :8001 -sTCP:LISTEN -t >/dev/null 2>&1 ; then
    echo "✅ Server già attivo su porta 8001"
else
    echo "🌐 Avvio server HTTP su porta 8001..."
    python3 -m http.server 8001 > /dev/null 2>&1 &
    sleep 2
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ DASHBOARD FORENSE ATTIVA!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 URL: http://localhost:8001/dashboard_forense.html"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 5 TAB DISPONIBILI:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  🎲 RUNS TEST"
echo "   • Test matematico di casualità sequenze turni/riposi"
echo "   • 4/6 staff con distribuzione NON casuale (p < 0.05)"
echo "   • Evidenza: Riposi raggruppati - NON casuali!"
echo ""
echo "2️⃣  ⚖️  INDICI PRIVILEGIO"
echo "   • Ranking complessivo dei privilegi"
echo "   • Formula: IP = (% Comodi × 2) + % Riposi - % Weekend - % Festivi"
echo "   • PAGANO più privilegiato (+1.34 Z-score)"
echo "   • MORALE più svantaggiato (-1.76 Z-score)"
echo ""
echo "3️⃣  😴 SEQUENZE RIPOSI"
echo "   • Analisi riposi consecutivi"
echo "   • VISSANI: max 8 giorni consecutivi"
echo "   • TAMBERI: max 7 giorni consecutivi"
echo "   • PACINI: 6 sequenze 3+ giorni"
echo ""
echo "4️⃣  🎯 TURNI COMODI"
echo "   • Distribuzione orari preferenziali (08:00-10:00)"
echo "   • MORALE: 38.6% turni comodi"
echo "   • VISSANI: 25.2% turni comodi"
echo "   • Differenza: 13.4 punti percentuali!"
echo ""
echo "5️⃣  📐 METODOLOGIA"
echo "   • Spiegazione test statistici usati"
echo "   • Runs Test (Wald-Wolfowitz)"
echo "   • Chi-quadrato (χ²)"
echo "   • Z-score e outliers"
echo "   • Formule matematiche complete"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚨 EVIDENZE PRINCIPALI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 RUNS TEST (Casualità):"
echo "   • CIRCELLI: p=0.0090 🚨 NON CASUALE"
echo "   • PACINI:   p=0.0174 🚨 NON CASUALE"
echo "   • PAGANO:   p=0.0324 🚨 NON CASUALE"
echo "   • VISSANI:  p=0.0334 🚨 NON CASUALE"
echo ""
echo "   Interpretazione: Riposi TROPPO RAGGRUPPATI per essere casuali!"
echo ""
echo "📍 DISPARITÀ TURNI COMODI:"
echo "   • MORALE:  38.6% (più favorito)"
echo "   • VISSANI: 25.2% (meno favorito)"
echo "   • Gap: 53% in più per MORALE!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📄 DOCUMENTI CORRELATI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   📊 REPORT_FORENSE_MANIPOLAZIONE.xlsx"
echo "      → Report Excel con tutti i dati e test"
echo ""
echo "   🐍 analisi_statistica_manipolazione.py"
echo "      → Script Python riproducibile"
echo ""
echo "   🌐 dashboard_forense.html"
echo "      → Dashboard interattiva (aperta ora!)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔒 GARANZIA: Tutti i calcoli Python (scipy/numpy) - ZERO AI!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Apri browser
open "http://localhost:8001/dashboard_forense.html"

echo "✅ Dashboard aperta nel browser!"
echo ""
echo "💡 Per fermare il server: killall Python (o chiudi questo terminale)"
echo ""

